// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: meta.proto

package metapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Mint               int64                  `protobuf:"varint,1,opt,name=mint,proto3" json:"mint,omitempty"`
	Maxt               int64                  `protobuf:"varint,2,opt,name=maxt,proto3" json:"maxt,omitempty"`
	Shards             int64                  `protobuf:"varint,3,opt,name=shards,proto3" json:"shards,omitempty"`
	ColumnsForName     map[string]*Columns    `protobuf:"bytes,4,rep,name=columnsForName,proto3" json:"columnsForName,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version            int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	ConvertedFromBLIDs []string               `protobuf:"bytes,6,rep,name=convertedFromBLIDs,proto3" json:"convertedFromBLIDs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetMint() int64 {
	if x != nil {
		return x.Mint
	}
	return 0
}

func (x *Metadata) GetMaxt() int64 {
	if x != nil {
		return x.Maxt
	}
	return 0
}

func (x *Metadata) GetShards() int64 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *Metadata) GetColumnsForName() map[string]*Columns {
	if x != nil {
		return x.ColumnsForName
	}
	return nil
}

func (x *Metadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Metadata) GetConvertedFromBLIDs() []string {
	if x != nil {
		return x.ConvertedFromBLIDs
	}
	return nil
}

type Columns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Columns) Reset() {
	*x = Columns{}
	mi := &file_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Columns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Columns) ProtoMessage() {}

func (x *Columns) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Columns.ProtoReflect.Descriptor instead.
func (*Columns) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{1}
}

func (x *Columns) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_meta_proto protoreflect.FileDescriptor

const file_meta_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"meta.proto\x12\x04meta\"\xb2\x02\n" +
	"\bMetadata\x12\x12\n" +
	"\x04mint\x18\x01 \x01(\x03R\x04mint\x12\x12\n" +
	"\x04maxt\x18\x02 \x01(\x03R\x04maxt\x12\x16\n" +
	"\x06shards\x18\x03 \x01(\x03R\x06shards\x12J\n" +
	"\x0ecolumnsForName\x18\x04 \x03(\v2\".meta.Metadata.ColumnsForNameEntryR\x0ecolumnsForName\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12.\n" +
	"\x12convertedFromBLIDs\x18\x06 \x03(\tR\x12convertedFromBLIDs\x1aP\n" +
	"\x13ColumnsForNameEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.meta.ColumnsR\x05value:\x028\x01\"#\n" +
	"\aColumns\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumnsB:Z8github.com/thanos-io/thanos-parquet-gateway/proto/metapbb\x06proto3"

var (
	file_meta_proto_rawDescOnce sync.Once
	file_meta_proto_rawDescData []byte
)

func file_meta_proto_rawDescGZIP() []byte {
	file_meta_proto_rawDescOnce.Do(func() {
		file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)))
	})
	return file_meta_proto_rawDescData
}

var file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meta_proto_goTypes = []any{
	(*Metadata)(nil), // 0: meta.Metadata
	(*Columns)(nil),  // 1: meta.Columns
	nil,              // 2: meta.Metadata.ColumnsForNameEntry
}
var file_meta_proto_depIdxs = []int32{
	2, // 0: meta.Metadata.columnsForName:type_name -> meta.Metadata.ColumnsForNameEntry
	1, // 1: meta.Metadata.ColumnsForNameEntry.value:type_name -> meta.Columns
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meta_proto_init() }
func file_meta_proto_init() {
	if File_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_proto_goTypes,
		DependencyIndexes: file_meta_proto_depIdxs,
		MessageInfos:      file_meta_proto_msgTypes,
	}.Build()
	File_meta_proto = out.File
	file_meta_proto_goTypes = nil
	file_meta_proto_depIdxs = nil
}
